apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}-dav
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  password: {{ include "helm.davPassword" . | b64enc }}
