apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helm.fullname" . }}-pics
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  {{- with .Values.persistence }}
  storageClassName: {{ .storageClassName }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .amount }}
  {{- end }}
