name: CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    environment: master
    steps:
      - uses: actions/checkout@v3
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.registry }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: build/Dockerfile
          tags: ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}:${{ github.ref_name }}
